[meta]
name = "catppuccin-mocha"
description = "Catppuccin Mocha - Soothing pastel theme for the high-spirited"
author = "Catppuccin"
source = "static"
mode = "dark"
wallpaper = "wallpaper.png"
gtk_theme = "Catppuccin-Mocha-Standard-Lavender-Dark"
icon_theme = "Papirus-Dark"
cursor_theme = "Catppuccin-Mocha-Lavender-Cursors"

[colors]
# Base colors mapped to Material Design 3 tokens
background = "#1e1e2e"
surface = "#1e1e2e"
surface_container = "#181825"
surface_container_low = "#11111b"
surface_container_high = "#313244"
surface_container_highest = "#45475a"
surface_container_lowest = "#11111b"
surface_bright = "#45475a"
surface_dim = "#1e1e2e"
surface_tint = "#b4befe"
surface_variant = "#313244"

primary = "#b4befe"
primary_container = "#45475a"
primary_fixed = "#b4befe"
primary_fixed_dim = "#89b4fa"
secondary = "#cba6f7"
secondary_container = "#45475a"
secondary_fixed = "#cba6f7"
secondary_fixed_dim = "#f5c2e7"
tertiary = "#f5c2e7"
tertiary_container = "#45475a"
tertiary_fixed = "#f5c2e7"
tertiary_fixed_dim = "#f38ba8"

on_surface = "#cdd6f4"
on_background = "#cdd6f4"
on_primary = "#1e1e2e"
on_primary_container = "#cdd6f4"
on_primary_fixed = "#1e1e2e"
on_primary_fixed_variant = "#313244"
on_secondary = "#1e1e2e"
on_secondary_container = "#cdd6f4"
on_secondary_fixed = "#1e1e2e"
on_secondary_fixed_variant = "#313244"
on_tertiary = "#1e1e2e"
on_tertiary_container = "#cdd6f4"
on_tertiary_fixed = "#1e1e2e"
on_tertiary_fixed_variant = "#313244"
on_surface_variant = "#a6adc8"

outline = "#6c7086"
outline_variant = "#45475a"
error = "#f38ba8"
error_container = "#45475a"
on_error = "#1e1e2e"
on_error_container = "#f38ba8"
inverse_surface = "#cdd6f4"
inverse_on_surface = "#1e1e2e"
inverse_primary = "#89b4fa"
scrim = "#000000"
shadow = "#000000"
source_color = "#b4befe"

[colors.terminal]
foreground = "#cdd6f4"
background = "#1e1e2e"
cursor = "#f5e0dc"
cursor_text = "#1e1e2e"
selection_fg = "#1e1e2e"
selection_bg = "#f5e0dc"
url_color = "#89b4fa"
color0 = "#45475a"
color1 = "#f38ba8"
color2 = "#a6e3a1"
color3 = "#f9e2af"
color4 = "#89b4fa"
color5 = "#f5c2e7"
color6 = "#94e2d5"
color7 = "#bac2de"
color8 = "#585b70"
color9 = "#f38ba8"
color10 = "#a6e3a1"
color11 = "#f9e2af"
color12 = "#89b4fa"
color13 = "#f5c2e7"
color14 = "#94e2d5"
color15 = "#a6adc8"

[colors.waybar]
power = "#a6e3a1"
network = "#94e2d5"
apps = "#89b4fa"
idle = "#cdd6f4"
notification = "#f9e2af"

[neovim]
colorscheme = "catppuccin-mocha"
