[meta]
name = "hacker-yoda"
description = "Deep purple Material You theme derived from hacker_yoda.jpeg"
author = "bpadair"
source = "static"
mode = "dark"
wallpaper = "hacker_yoda.jpeg"
gtk_theme = "Material-Black-Lime"
icon_theme = "breeze-dark"
cursor_theme = "default"

[colors]
background = "#131318"
error = "#ffb4ab"
error_container = "#93000a"
inverse_on_surface = "#313036"
inverse_primary = "#5c5891"
inverse_surface = "#e5e1e9"
on_background = "#e5e1e9"
on_error = "#690005"
on_error_container = "#ffdad6"
on_primary = "#2e295f"
on_primary_container = "#e4dfff"
on_primary_fixed = "#18124a"
on_primary_fixed_variant = "#444078"
on_secondary = "#302e41"
on_secondary_container = "#e4dff9"
on_secondary_fixed = "#1b192c"
on_secondary_fixed_variant = "#474459"
on_surface = "#e5e1e9"
on_surface_variant = "#c8c5d0"
on_tertiary = "#482537"
on_tertiary_container = "#ffd8e8"
on_tertiary_fixed = "#2f1122"
on_tertiary_fixed_variant = "#613b4e"
outline = "#928f99"
outline_variant = "#47464f"
primary = "#c6c0ff"
primary_container = "#444078"
primary_fixed = "#e4dfff"
primary_fixed_dim = "#c6c0ff"
scrim = "#000000"
secondary = "#c8c3dc"
secondary_container = "#474459"
secondary_fixed = "#e4dff9"
secondary_fixed_dim = "#c8c3dc"
shadow = "#000000"
source_color = "#1b1a23"
surface = "#131318"
surface_bright = "#3a383e"
surface_container = "#201f25"
surface_container_high = "#2a292f"
surface_container_highest = "#35343a"
surface_container_low = "#1c1b20"
surface_container_lowest = "#0e0e13"
surface_dim = "#131318"
surface_tint = "#c6c0ff"
surface_variant = "#47464f"
tertiary = "#ebb8cf"
tertiary_container = "#613b4e"
tertiary_fixed = "#ffd8e8"
tertiary_fixed_dim = "#ebb8cf"

[colors.terminal]
foreground = "#e5e1e9"
background = "#131318"
cursor = "#e5e1e9"
cursor_text = "#c8c5d0"
selection_fg = "#302e41"
selection_bg = "#c8c3dc"
url_color = "#c6c0ff"
color0 = "#4c4c4c"
color1 = "#ac8a8c"
color2 = "#8aac8b"
color3 = "#aca98a"
color4 = "#c6c0ff"
color5 = "#ac8aac"
color6 = "#8aacab"
color7 = "#f0f0f0"
color8 = "#262626"
color9 = "#c49ea0"
color10 = "#9ec49f"
color11 = "#c4c19e"
color12 = "#a39ec4"
color13 = "#c49ec4"
color14 = "#9ec3c4"
color15 = "#e7e7e7"

[colors.waybar]
# Custom waybar icon colors (preserved from original)
power = "#00ff00"
network = "#00ffff"
apps = "#0B57A4"
idle = "#ffffff"
notification = "#ffff00"

[neovim]
colorscheme = "tokyonight-night"
